name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pybm
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0
